/**
 * tutorial/lesson-brain.mjs — Hathor's lesson-scoped thinking for comments on the Instructional Series.
 *
 * What it gives the call handler:
 *
 *   lessonContext(lesson, registry)  the lesson's body, FAQ, check explanation, and a brief of the
 *                                    lessons it requires — what her prompt carries when a comment lands
 *                                    on lesson X.
 *   siteMapExcerpt(query, text)      the few site-map entries relevant to a question (the site map is
 *                                    generated by tutorial/site-map.mjs from the live tool registry,
 *                                    the host routes, the wiki and the Studio nav).
 *   faqMatch(question, faq)          FAQ first — a lexical match against the lesson's own FAQ.
 *   protect()/restore()              chain terms, @names and URLs are swapped for ⟦n⟧ tokens before any
 *                                    translation and verified on the way back, so MELEK, PRANA, links and
 *                                    usernames can never be "translated".
 *   createLessonBrain(cfg)           classify / answer / translate / voice through the ONE brain.
 *
 * PRIVATE, LOCAL INFERENCE ONLY. The lesson drafts are private until the operator approves them, and
 * this module never calls an external model API. Two transports, both local:
 *   • 'agency' — the hathor-agency service's POST /lesson (surface 'melek'), used when its /health
 *                advertises the `lesson` feature. The service answers with its local model.
 *   • 'ollama' — the local Ollama on the same host (default model granite-melek3), used when the running
 *                agency predates the `lesson` feature. Same model, same box, nothing leaves it.
 * There is deliberately no third transport.
 *
 * House style: ESM, injectable fetch, soft-fail-never-throw (every call returns null/fallback on error),
 * offline-testable.
 */

import { classifyIntentFallback, detectLanguage, languageName } from './lang.mjs';

export const DEFAULT_AGENCY_URL = 'http://127.0.0.1:8175';
export const DEFAULT_OLLAMA_URL = 'http://127.0.0.1:11434';
export const DEFAULT_LOCAL_MODEL = 'granite-melek3';

// ---- lesson context ------------------------------------------------------------------------------

const clip = (s, n) => { const t = String(s || '').trim(); return t.length > n ? `${t.slice(0, n - 1)}…` : t; };

/** Strip HTML comments / image-slot notes from a lesson body before it goes into a prompt. */
function cleanBody(md) {
  return String(md || '').replace(/<!--[\s\S]*?-->/g, '').replace(/\n{3,}/g, '\n\n').trim();
}

/**
 * The lesson-scoped context for a prompt. Body is clipped (a 2B model has a small window); FAQ and the
 * check explanation are always included in full because they are the most answer-dense part.
 */
export function lessonContext(lesson, registry = null, { maxBody = 3500 } = {}) {
  if (!lesson) return '';
  const parts = [`LESSON ${lesson.n}: ${lesson.title}`, `Post: ${lesson.url || lesson.permlink}`];
  const reqs = registry && typeof registry.prerequisitesOf === 'function'
    ? registry.prerequisitesOf(lesson.id).filter((l) => (lesson.requires || []).includes(l.id)) : [];
  if (reqs.length) {
    parts.push(`Builds on: ${reqs.map((r) => `Lesson ${r.n} "${r.title}"${r.tryThis ? ` (task: ${clip(r.tryThis, 160)})` : ''}`).join('; ')}`);
  }
  parts.push('', 'LESSON TEXT:', clip(cleanBody(lesson.body), maxBody));
  if (lesson.check?.explain) parts.push('', `HOW I CHECK THIS LESSON: ${lesson.check.explain}`);
  if (lesson.faq?.length) {
    parts.push('', 'FAQ:');
    for (const f of lesson.faq) parts.push(`Q: ${f.q}`, `A: ${f.a}`);
  }
  return parts.join('\n');
}

// ---- site map -------------------------------------------------------------------------------------

const STOP = new Set(['the', 'and', 'for', 'that', 'with', 'this', 'from', 'are', 'was', 'has', 'not', 'can', 'all', 'but',
  'you', 'your', 'our', 'its', 'how', 'what', 'where', 'when', 'why', 'which', 'who', 'does', 'did', 'have', 'into', 'than',
  'then', 'also', 'just', 'there', 'here', 'about', 'they', 'them', 'will', 'would', 'could', 'should', 'make', 'made', 'want']);
const terms = (s) => [...new Set((String(s || '').toLowerCase().match(/[a-z0-9][a-z0-9-]{2,}/g) || []).filter((w) => !STOP.has(w)))];

/** Pick the site-map lines (one entry per line, "- ...") most relevant to a query. */
export function siteMapExcerpt(query, siteMapText, { k = 6 } = {}) {
  const q = terms(query);
  if (!q.length || !siteMapText) return '';
  const lines = String(siteMapText).split('\n').filter((l) => l.startsWith('- '));
  const scored = lines.map((l) => {
    const low = l.toLowerCase();
    return { l, s: q.reduce((n, t) => n + (low.includes(t) ? 1 : 0), 0) };
  }).filter((x) => x.s > 0).sort((a, b) => b.s - a.s).slice(0, k);
  return scored.map((x) => x.l).join('\n');
}

// ---- FAQ ------------------------------------------------------------------------------------------

/**
 * FAQ first. Lexical overlap between the question (ideally its English gloss) and each FAQ question.
 * Returns the best `{ q, a, score }` at or above `min`, else null.
 */
export function faqMatch(question, faq = [], { min = 0.5 } = {}) {
  const q = terms(question);
  if (!q.length || !faq.length) return null;
  let best = null;
  for (const f of faq) {
    const fq = terms(f.q);
    if (!fq.length) continue;
    const shared = q.filter((t) => fq.includes(t) || fq.some((x) => x.length > 4 && t.length > 4 && (x.startsWith(t.slice(0, 5)) || t.startsWith(x.slice(0, 5))))).length;
    const score = shared / Math.min(q.length, fq.length);
    if (!best || score > best.score) best = { q: f.q, a: f.a, score };
  }
  return best && best.score >= min && terms(best.q).length ? best : null;
}

// ---- protected translation ------------------------------------------------------------------------

// Terms that must never be translated. Order matters (longest first).
export const KEEP_TERMS = ['MELEK.Salon', 'melek.salon', 'MELEK POWER', 'MELEK-Signer', 'MELEK-Engine', 'MELEK', 'PRANA', 'KULA', 'SoapBox', 'Hathor', 'Pentecaust', 'Hierophant'];

/**
 * Swap URLs, markdown link targets, @usernames and KEEP_TERMS for ⟦n⟧ tokens.
 * @returns {{ text: string, tokens: string[] }}
 */
export function protect(text) {
  const tokens = [];
  const put = (m) => { tokens.push(m); return `⟦${tokens.length - 1}⟧`; };
  let t = String(text || '');
  t = t.replace(/\]\((https?:\/\/[^)\s]+)\)/g, (_m, u) => `](${put(u)})`);
  t = t.replace(/https?:\/\/[^\s)\]]+/g, put);
  t = t.replace(/(^|[^\w@])@[a-z0-9][a-z0-9.-]{1,15}\b/gi, (m, pre) => `${pre}${put(m.slice(pre.length))}`);
  for (const term of KEEP_TERMS) {
    t = t.replace(new RegExp(`(?<![\\w⟦])${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![\\w⟧])`, 'g'), put);
  }
  return { text: t, tokens };
}

/** Put the tokens back. Returns null if the translation lost or invented any token. */
export function restore(text, tokens) {
  const s = String(text || '');
  const seen = [...s.matchAll(/⟦(\d+)⟧/g)].map((m) => Number(m[1]));
  if (seen.some((i) => i >= tokens.length)) return null;
  for (let i = 0; i < tokens.length; i++) if (!seen.includes(i)) return null;
  return s.replace(/⟦(\d+)⟧/g, (_m, i) => tokens[Number(i)]);
}

// Scripts a translation into these languages must actually contain.
const SCRIPT_OF = { bn: /[ঀ-৿]/, hi: /[ऀ-ॿ]/, ar: /[؀-ۿ]/, ur: /[؀-ۿ]/,
  ru: /[Ѐ-ӿ]/, zh: /[一-鿿]/, ja: /[぀-ヿ一-鿿]/, ko: /[가-힯]/, th: /[฀-๿]/ };

/** Does `out` plausibly read as language `lang`? (Script check for non-Latin; detector for Latin.) */
export function looksLike(out, lang) {
  const s = String(out || '');
  if (!s.trim()) return false;
  if (SCRIPT_OF[lang]) {
    const letters = (s.replace(/⟦\d+⟧|https?:\/\/\S+|@[\w.-]+/g, '').match(/\p{L}/gu) || []).length;
    const inScript = (s.match(new RegExp(SCRIPT_OF[lang].source, 'gu')) || []).length;
    return letters > 0 && inScript / letters >= 0.4;
  }
  const d = detectLanguage(s);
  return d.lang === lang || d.lang === 'und';
}

// ---- the brain client -----------------------------------------------------------------------------

function parseJsonLoose(s) {
  if (s && typeof s === 'object') return s;
  const m = String(s || '').match(/\{[\s\S]*\}/);
  if (!m) return null;
  try { return JSON.parse(m[0]); } catch { return null; }
}

const INTENTS = new Set(['claim', 'question', 'other']);

/**
 * @param {object} cfg
 * @param {'auto'|'agency'|'ollama'|'off'} [cfg.mode]  default 'auto' (agency if it has the `lesson` feature)
 * @param {string} [cfg.agencyUrl] [cfg.ollamaUrl] [cfg.model]
 * @param {Function} [cfg.fetch]  injectable
 * @param {number} [cfg.timeoutMs] per call (a 2B model on CPU: tens of seconds)
 * @param {Function} [cfg.log]
 */
export function createLessonBrain(cfg = {}) {
  const f = cfg.fetch || ((...a) => globalThis.fetch(...a));
  const agencyUrl = String(cfg.agencyUrl || process.env.HATHOR_AGENCY_URL || DEFAULT_AGENCY_URL).replace(/\/$/, '');
  const ollamaUrl = String(cfg.ollamaUrl || process.env.OLLAMA_URL || DEFAULT_OLLAMA_URL).replace(/\/$/, '');
  const model = cfg.model || process.env.HATHOR_LOCAL_MODEL || DEFAULT_LOCAL_MODEL;
  const timeoutMs = Number(cfg.timeoutMs) || 90_000;
  const log = typeof cfg.log === 'function' ? cfg.log : () => {};
  // GATED: the model is OFF unless HATHOR_LLM=1 (operator 2026-09-26: "Hathor is not at all ready to be
  // wired to actually read and respond — we need a GPU"). Off means complete() returns null without any
  // network call, so classify() falls to the multilingual keyword floor, translate() keeps English, and
  // answer()/voice() are silent — the Phase-2 deterministic bot. An explicit cfg.mode (tests) wins.
  const llmOn = String(cfg.llm ?? process.env.HATHOR_LLM ?? '0') === '1';
  const mode = cfg.mode || (llmOn ? (process.env.LESSON_BRAIN_MODE || 'auto') : 'off');
  let resolved = mode === 'auto' ? null : mode;
  const stats = { calls: 0, failures: 0, transport: resolved };

  async function post(url, body) {
    const ctl = typeof AbortController === 'function' ? new AbortController() : null;
    const timer = ctl ? setTimeout(() => ctl.abort(), timeoutMs) : null;
    try {
      const r = await f(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body), signal: ctl?.signal });
      if (r && r.ok === false) return null;
      return await r.json();
    } catch { return null; } finally { if (timer) clearTimeout(timer); }
  }

  async function transport() {
    if (resolved) return resolved;
    try {
      const r = await f(`${agencyUrl}/health`, {});
      const j = await r.json();
      resolved = Array.isArray(j?.features) && j.features.includes('lesson') ? 'agency' : 'ollama';
    } catch { resolved = 'ollama'; }
    stats.transport = resolved;
    log(`[lesson-brain] transport=${resolved}`);
    return resolved;
  }

  /** One local completion. `json:true` asks for a JSON object. Returns string|null. */
  async function complete(prompt, { json = false, task = 'raw', from = null, context = '', lang = 'en', question = '' } = {}) {
    if (mode === 'off') return null;
    stats.calls++;
    const t = await transport();
    let out = null;
    if (t === 'agency') {
      const j = await post(`${agencyUrl}/lesson`, { task, prompt, json, from, context, lang, question, surface: 'melek' });
      out = j && j.ok ? j.text ?? j.reply ?? null : null;
    } else {
      const j = await post(`${ollamaUrl}/api/generate`, {
        model, prompt, stream: false, ...(json ? { format: 'json' } : {}),
        options: { temperature: json ? 0 : 0.3, num_predict: json ? 200 : 400 },
      });
      out = j && typeof j.response === 'string' ? j.response : null;
    }
    if (!out || !String(out).trim()) { stats.failures++; return null; }
    return String(out).trim();
  }

  /**
   * Intent + language + an English gloss. The deterministic fallback runs first (free) and the model
   * refines it; if the model is silent or returns junk, the fallback stands.
   */
  async function classify(text, { lesson = null } = {}) {
    const fb = classifyIntentFallback(text, { callPhrase: lesson?.callPhrase || '' });
    const offline = detectLanguage(text);
    const prompt = [
      'You label comments left under a tutorial lesson. Reply with ONLY a JSON object:',
      '{"intent":"claim|question|other","lang":"<ISO 639-1 code of the comment language>","english":"<the comment in English>","lesson":<lesson number if the comment names one, else null>}',
      'claim = they say they finished or did the task, or ask to be checked (in any language, any wording).',
      'question = they ask something. other = thanks, greetings, chat.',
      lesson ? `Lesson: ${lesson.title}` : '',
      `Comment: """${clip(text, 800)}"""`,
    ].filter(Boolean).join('\n');
    const raw = await complete(prompt, { json: true, task: 'classify' });
    const j = parseJsonLoose(raw);
    const intent = j && INTENTS.has(String(j.intent).toLowerCase()) ? String(j.intent).toLowerCase() : null;
    // The offline script detector is more reliable than a 2B model for non-Latin scripts; the model
    // breaks ties only where the detector was unsure.
    let lang = offline.confidence >= 0.5 ? offline.lang : fb.lang;
    if ((lang === 'und' || offline.confidence < 0.5) && j && /^[a-z]{2}$/i.test(String(j.lang || ''))) lang = String(j.lang).toLowerCase();
    if (lang === 'und') lang = 'en';
    const english = j && typeof j.english === 'string' && j.english.trim() ? j.english.trim() : (lang === 'en' ? String(text) : '');
    const lessonNumber = j && Number.isFinite(Number(j.lesson)) && j.lesson !== null ? Number(j.lesson) : null;
    // A strong keyword claim is not overruled by a model that reads "check me" as "other".
    const finalIntent = intent && !(fb.intent === 'claim' && fb.confidence >= 0.7 && intent === 'other') ? intent : fb.intent;
    return { intent: finalIntent, lang, english, lessonNumber, via: intent ? 'brain' : fb.via, fallback: fb };
  }

  /** Translate English → `lang`, with protected tokens. Returns the translation, or null (keep English). */
  async function translate(text, lang) {
    if (!lang || lang === 'en' || lang === 'und') return text;
    const name = languageName(lang);
    if (!name) return null;
    const { text: guarded, tokens } = protect(text);
    const prompt = [
      `Translate the text below into ${name}. Keep every token like ⟦0⟧ exactly as written, in a sensible place.`,
      'Keep markdown formatting. Output ONLY the translation, nothing else.',
      '', 'TEXT:', guarded,
    ].join('\n');
    const out = await complete(prompt, { task: 'translate', lang });
    if (!out) return null;
    const back = restore(out.replace(/^(translation|traducción|অনুবাদ)\s*:\s*/i, ''), tokens);
    if (!back || !looksLike(back, lang)) { log(`[lesson-brain] translation to ${lang} rejected (tokens or script)`); return null; }
    return back;
  }

  /** Answer a question from the lesson context (English). Returns string|null. */
  async function answer({ question, english = '', lesson = null, context = '', siteMap = '', from = null } = {}) {
    const q = english || question;
    const prompt = [
      'You are Hathor, the MELEK AI Witness: warm, calm, precise. A reader commented on your lesson with a question.',
      'Answer ONLY from the lesson facts below. Be concrete: name the buttons, pages and links. 2 to 5 sentences.',
      'If the facts do not cover it, say so plainly and point to the closest step in the lesson. Never invent links.',
      '', 'LESSON FACTS:', context || lessonContext(lesson),
      siteMap ? `\nSITE MAP (relevant entries):\n${siteMap}` : '',
      '', `QUESTION: ${clip(q, 800)}`, '', 'ANSWER (in English):',
    ].join('\n');
    return complete(prompt, { task: 'answer', from, context, question: q });
  }

  /** One sentence in her own register for a moment (a pass, a gentle "not yet"). Returns string|null. */
  async function voice(kind, facts = {}) {
    const prompt = [
      'You are Hathor, the MELEK AI Witness: warm, calm, slightly archaic, never corporate. Write ONE short sentence (under 30 words), no greeting formula, no emoji, no hashtags.',
      kind === 'pass' ? `Moment: @${facts.account} just finished your lesson "${facts.lesson}". Acknowledge the work itself.`
        : kind === 'fail' ? `Moment: @${facts.account} asked you to check your lesson "${facts.lesson}", and it is not finished yet. Be encouraging, not scolding.`
          : `Moment: ${facts.moment || 'a reader spoke to you'}.`,
      'SENTENCE:',
    ].join('\n');
    const out = await complete(prompt, { task: 'voice' });
    if (!out) return null;
    const line = out.split('\n').map((s) => s.trim()).filter(Boolean)[0] || '';
    // Refuse anything that smuggles links/handles or runs long — the facts block carries those.
    if (!line || line.length > 240 || /https?:|⟦/.test(line)) return null;
    return line.replace(/^["“]|["”]$/g, '');
  }

  return { classify, translate, answer, voice, complete, transport, stats, get model() { return model; }, get enabled() { return mode !== 'off'; } };
}
