// cosmologies.mjs — WORLD AGES, EMERGENCE, AND DESCENT: the accounts of how things came to be.
//
// Seventh in the series with pantheon-map.mjs, divine-sets.mjs, correspondences.mjs, time-cycles.mjs,
// divine-attributes.mjs and day-signs.mjs.
//
// THE GAP THIS FILLS. divine-sets.mjs counts gods — sevens, ogdoads, enneads, twelves — and holds
// eighteen sets, **not one of them from the Americas or Polynesia**. Nothing anywhere in the corpus
// held a WORLD-AGE or an EMERGENCE account, which is the form most of the world's cosmology actually
// takes. A pantheon says who the gods are. A cosmology says what happened, in what order, and how many
// times it has already ended.
//
// ⭐ THE OBSERVATION, and it is divine-sets.mjs's thesis holding in a second domain.
//
// That file found that the ancient world does not organise its gods into lists, it organises them into
// COUNTS — the number comes first and the roster is filled in locally. World-ages do the same thing:
//
//   FIVE — Hesiod's ages of man; the Aztec Five Suns
//   FOUR — the Hindu yugas; the Hopi and Navajo worlds
//
// Hesiod and the Mexica are not in contact. The count recurs because a small integer with a decline
// built into it is a shape human beings reach for, not because somebody carried it across an ocean.
// Recording the count separately from the roster is what makes that visible rather than mysterious —
// and it is the honest alternative to the diffusion argument day-signs.mjs already had to dismantle
// once (see ARTIFACTS there: ōcēlōtl means jaguar, and the "4 Tiger" anomaly is a translation error).
//
// ⭐ THE SECOND FORM, which the Greek and Egyptian material does not prepare you for.
//
// A GENEALOGICAL cosmogony does not narrate events — it recites descent, and it does not stop at the
// gods. The Hawaiian Kumulipo runs from the coral polyp through the sea, the land and the birds to the
// chiefs who commissioned it, in one unbroken line. The cosmology IS the genealogy, and its function is
// to seat a living ruling line inside creation. That is why Hawaiian royal descent belongs in a file
// about cosmology rather than in one about kings: for the aliʻi they are the same document.
//
// ⚠️ RESTRICTED MATERIAL — read before extending this file.
//
// Several traditions here are living, and portions of their cosmology are deliberately not public.
// Hopi and Navajo emergence accounts have esoteric registers held by initiates and clans; Yaqui Waehma
// material is ceremonially restricted. Published summaries exist and are cited, but "an ethnographer
// printed it in 1904" is not the same as "the community consented to its circulation." Every entry
// carries `restricted`, and `publicSafe()` filters on it. **Do not add detail from a restricted
// register because a source is out of copyright.** Copyright expiry is not consent.
//
//   import { COSMOLOGIES, FORMS, byCount, sharedCounts, publicSafe } from './cosmologies.mjs'
//   node integrations/cosmologies.mjs counts

import { fileURLToPath } from 'node:url';
import { TIERS, tierRank } from './pantheon-map.mjs';

export { TIERS, tierRank };

export const esc = (s) => String(s == null ? '' : s)
  .replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/** The shapes a cosmology takes. The form matters more than the content for comparison. */
export const FORMS = Object.freeze({
  'world-ages': 'a counted series of worlds, each ending in a catastrophe',
  emergence: 'ascent through stacked worlds into this one',
  genealogical: 'an unbroken recitation of descent, from the first thing to the living',
  'separation': 'an original unity divided — sky from earth, light from dark',
  'craft': 'a maker forms the world from material or from a body',
});

export const COSMOLOGIES = [
  // ── the Americas ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'five-suns', label: 'The Five Suns (Nahui Ollin)', tradition: 'aztec', form: 'world-ages',
    count: 5, attested: 1500, tier: 'epigraphic', restricted: false,
    source: 'Leyenda de los Soles (1558); Codex Chimalpopoca; the Piedra del Sol; Sahagún, Florentine Codex Book VII',
    members: ['Nahui Ōcēlōtl — 4 Jaguar', 'Nahui Ehēcatl — 4 Wind', 'Nahui Quiyahuitl — 4 Rain',
      'Nahui Atl — 4 Water', 'Nahui Ōllin — 4 Movement (the present sun, to end in earthquake)'],
    note: '⚠️ The first age is 4 JAGUAR, not "4 Tiger" — see ARTIFACTS in day-signs.mjs. Every age is '
      + 'named with the number four plus a day-sign, so the series is generated by the calendar rather '
      + 'than narrated independently of it. The present world is the fifth and is expected to end.',
  },
  {
    id: 'hopi-worlds', label: 'The Hopi worlds and the emergence', tradition: 'hopi', form: 'emergence',
    count: 4, attested: 1905, tier: 'attested', restricted: true,
    source: 'Voth, Traditions of the Hopi (Field Columbian Museum, 1905); later popular retellings, notably Waters, Book of the Hopi (1963), which Hopi commentators have disputed as unrepresentative',
    members: ['first world', 'second world', 'third world', 'fourth world — the present'],
    note: '⚠️ RESTRICTED REGISTER. Ceremonial detail is held by clan and society and is not public. '
      + 'Waters (1963) is the version most people have read and is the least reliable — treat any claim '
      + 'traceable only to it as unsourced. Count and structure are safe; specifics are not ours to give.',
  },
  {
    id: 'dine-worlds', label: 'Diné Bahaneʼ — the emergence through the worlds', tradition: 'navajo', form: 'emergence',
    count: 4, attested: 1897, tier: 'attested', restricted: true,
    source: 'Matthews, Navaho Legends (American Folk-Lore Society, 1897); Zolbrod, Diné bahaneʼ (1984)',
    members: ['black world', 'blue world', 'yellow world', 'glittering world — the present'],
    note: '⚠️ RESTRICTED REGISTER. The account is tied to ceremonial contexts with their own seasons and '
      + 'authorities. Colour-named worlds are widely published; the ceremonial matter is not. Note the '
      + 'structural rhyme with the Hopi four — neighbouring traditions, and the count is shared.',
  },
  {
    id: 'yaqui-huya-ania', label: 'Huya aniya and the Sea Ania (the flower world)', tradition: 'yaqui', form: 'separation',
    count: null, attested: 1645, tier: 'attested', restricted: true,
    source: 'Pérez de Ribas, Historia de los triunphos (1645) for the contact-era record; modern ethnography incl. Spicer, The Yaquis: A Cultural History (1980); Evers & Molina, Yaqui Deer Songs / Maso Bwikam (1987)',
    members: ['huya aniya — the wilderness world', 'sea ania — the flower world', 'yo ania — the enchanted world'],
    note: '⚠️ RESTRICTED. Waehma (the Lenten ceremonial cycle) is not public material and is not '
      + 'summarised here. The aniya framework is published by Yaqui authors themselves — Evers & Molina '
      + 'is the citation to prefer precisely because it is collaborative. NOT a world-age scheme: this '
      + 'is coexisting worlds, not a sequence, which is why `count` is null rather than guessed.',
  },

  // ── Polynesia ─────────────────────────────────────────────────────────────────────────────────
  {
    id: 'kumulipo', label: 'The Kumulipo', tradition: 'hawaiian', form: 'genealogical',
    count: 16, attested: 1700, tier: 'attested', restricted: false,
    source: 'Composed for Kalaninuiʻīamamao (c. early 18th c.); transcribed and published by Kalākaua (1889); translated by Liliʻuokalani during her imprisonment at ʻIolani Palace (published 1897); Beckwith, The Kumulipo: A Hawaiian Creation Chant (1951)',
    members: ['seven wā of pō (darkness)', 'nine wā of ao (light)'],
    note: '⭐ THE GENEALOGICAL FORM, and the reason royal descent is a cosmological question here. Over '
      + 'two thousand lines proceeding from the coral polyp through sea life, plants, birds and animals '
      + 'to human beings and then to the chiefs — one unbroken line. It does not narrate a creation; it '
      + 'RECITES A DESCENT, and its function is to seat a living ruling line inside creation itself. '
      + 'Its two translators are a reigning king and a deposed queen: Kalākaua published it as a claim '
      + 'of legitimacy, and Liliʻuokalani translated it under house arrest after the overthrow. The '
      + 'text is a political instrument as well as a cosmology, and was used as one by both of them.',
  },

  // ── the comparanda that make the counts visible ───────────────────────────────────────────────
  {
    id: 'hesiodic-ages', label: 'The five ages of man', tradition: 'greek', form: 'world-ages',
    count: 5, attested: -700, tier: 'attested', restricted: false,
    source: 'Hesiod, Works and Days 106–201',
    members: ['golden', 'silver', 'bronze', 'the heroes', 'iron — the present'],
    note: 'FIVE, like the Aztec suns, and independent of them. Hesiod also breaks his own metal scheme '
      + 'to insert the age of heroes fourth — the sequence is not a clean decline, and the interruption '
      + 'is evidence the scheme was assembled rather than inherited whole.',
  },
  {
    id: 'yugas', label: 'The four yugas', tradition: 'hindu', form: 'world-ages',
    count: 4, attested: -300, tier: 'attested', restricted: false,
    source: 'Mahābhārata, Śānti Parva; Manusmṛti 1.68–86; the Purāṇas for the developed chronology',
    members: ['Satya (Kṛta)', 'Tretā', 'Dvāpara', 'Kali — the present'],
    note: 'FOUR, with a declining ratio 4:3:2:1 that is explicitly numerical — the only world-age scheme '
      + 'here that states its own arithmetic. Cyclic rather than terminal: the series repeats, where '
      + 'Hesiod and the Five Suns both run toward an end.',
  },
  {
    id: 'zoroastrian-ages', label: 'The twelve millennia', tradition: 'zoroastrian', form: 'world-ages',
    count: 4, attested: 900, tier: 'attested', restricted: false,
    source: 'Bundahišn (9th-c. compilation of older material); the scheme is four periods of three thousand years',
    members: ['creation', 'mixture', 'separation', 'the making wonderful (frašōkərəti)'],
    note: 'FOUR again, and the one that ends in restoration rather than destruction.',
  },
];

// ── lookups ────────────────────────────────────────────────────────────────────────────────────
const norm = (s) => String(s == null ? '' : s).trim().toLowerCase();

export const getCosmology = (id) => COSMOLOGIES.find((c) => c.id === norm(id)) || null;
export const TRADITIONS = [...new Set(COSMOLOGIES.map((c) => c.tradition))].sort();
export const byTradition = (t) => COSMOLOGIES.filter((c) => c.tradition === norm(t));
export const byForm = (f) => COSMOLOGIES.filter((c) => c.form === norm(f));
export const byCount = (n) => COSMOLOGIES.filter((c) => c.count === n);

/** Entries safe to reproduce in public without a community's consent question. */
export const publicSafe = () => COSMOLOGIES.filter((c) => !c.restricted);
export const restricted = () => COSMOLOGIES.filter((c) => c.restricted);

/**
 * ⭐ Counts shared by traditions that are not in contact — divine-sets.mjs's thesis, in a second domain.
 * Returns the count, who uses it, and an explicit refusal to treat the coincidence as transmission.
 */
export function sharedCounts() {
  const byN = new Map();
  for (const c of COSMOLOGIES) {
    if (c.count == null) continue;
    if (!byN.has(c.count)) byN.set(c.count, []);
    byN.get(c.count).push({ id: c.id, tradition: c.tradition });
  }
  const shared = [...byN.entries()]
    .filter(([, list]) => new Set(list.map((x) => x.tradition)).size > 1)
    .map(([n, list]) => ({ count: n, traditions: list }))
    .sort((a, b) => a.count - b.count);
  return {
    shared,
    reading: 'The count recurs; the roster does not. Hesiod and the Mexica share FIVE and share nothing '
      + 'else — no names, no order, no mechanism of ending. A small integer with a decline built into it '
      + 'is a shape people reach for. Treat a shared count as a fact about counting, not as evidence of '
      + 'contact, unless something ELSE travels with it — a loanword, a technique, a name.',
  };
}

/** Shape check. Returns problems; never throws. */
export function validate() {
  const problems = [];
  for (const c of COSMOLOGIES) {
    const id = c.id;
    if (!Object.hasOwn(FORMS, c.form)) problems.push(`${id}: unknown form ${c.form}`);
    if (!TIERS.includes(c.tier)) problems.push(`${id}: unknown tier ${c.tier}`);
    if (!c.source) problems.push(`${id}: no source`);
    if (typeof c.restricted !== 'boolean') problems.push(`${id}: restricted must be explicit`);
    if (c.count != null && !Number.isInteger(c.count)) problems.push(`${id}: count is not an integer`);
    // A restricted entry must say what is withheld, or the flag is decoration.
    if (c.restricted && !/RESTRICTED/i.test(String(c.note))) problems.push(`${id}: restricted but the note does not say what is withheld`);
  }
  return { ok: problems.length === 0, problems };
}

export function handler(req, res) {
  res.statusCode = 200;
  res.setHeader('content-type', 'application/json; charset=utf-8');
  res.end(JSON.stringify({
    ok: true, service: 'cosmologies',
    counts: { cosmologies: COSMOLOGIES.length, traditions: TRADITIONS.length, restricted: restricted().length },
    forms: FORMS,
    note: 'world ages, emergence and descent. A shared count is a fact about counting, not evidence of '
        + 'contact. Restricted registers are flagged and not reproduced.',
  }, null, 2));
}

export default { COSMOLOGIES, FORMS, TRADITIONS, getCosmology, byTradition, byForm, byCount, publicSafe, restricted, sharedCounts, validate, handler };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv[2] === 'counts') {
    const s = sharedCounts();
    for (const r of s.shared) console.log(`${r.count}: ${r.traditions.map((t) => t.tradition).join(', ')}`);
    console.log(`\n${s.reading}`);
  } else {
    const v = validate();
    console.log(`${COSMOLOGIES.length} cosmologies · ${TRADITIONS.length} traditions · ${restricted().length} restricted · valid: ${v.ok}`);
    for (const c of COSMOLOGIES) {
      console.log(`  ${String(c.count ?? '-').padStart(2)}  ${c.label.padEnd(44)} ${c.form.padEnd(13)} ${c.restricted ? '⚠️ restricted' : ''}`);
    }
  }
}
