// day-signs.test.mjs — OFFLINE, pure data.
//
// The load-bearing tests are the ARTEFACT tests. This file exists to carry a correction to a claim
// the knowledge corpus repeats in five places, and the correction is only worth anything if it is
// stated precisely, scoped honestly, and cannot silently rot back into the original error.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  SYSTEMS, ARTIFACTS, TIERS, getSystem, byTradition, TRADITIONS,
  animalSigns, hourGods, sharedAnimals, artifacts, dissolved, validate, handler, esc,
} from './day-signs.mjs';

// --- shape -------------------------------------------------------------------

test('every system carries n, a source, a tier and a date', () => {
  const v = validate();
  assert.equal(v.ok, true, v.problems.join('\n'));
});

test('the tier ladder is imported from pantheon-map, not restated', async () => {
  const pm = await import('./pantheon-map.mjs');
  assert.deepEqual(TIERS, pm.TIERS);
});

test('an animal system lists exactly n members — a miscount would corrupt every comparison', () => {
  for (const s of animalSigns()) assert.equal(s.animalMembers.length, s.n, `${s.id} has ${s.animalMembers.length} of ${s.n}`);
});

// --- ⭐ the correction --------------------------------------------------------

test('ōcēlōtl is recorded as JAGUAR, and the Aztec day-sign list says so inline', () => {
  const t = getSystem('tonalpohualli');
  const sign = t.animalMembers.find((m) => /ocelotl/i.test(m));
  assert.match(sign, /JAGUAR/, 'the day-sign member must name the jaguar where a reader will see it');
  assert.ok(!/tiger/i.test(t.animalMembers.join(' ')), 'no tiger may appear in the Aztec list');
});

test('the tiger claim is marked DISSOLVED and names where the corpus repeats it', () => {
  const a = ARTIFACTS.find((x) => x.id === 'aztec-tiger');
  assert.equal(a.verdict, 'dissolved');
  assert.match(a.actualMeaning, /jaguar/i);
  assert.match(a.term, /ōcēlōtl|ocelotl/);
  assert.ok(a.appearsIn.length >= 4, 'the corpus files carrying the claim must be listed so they can be found');
  for (const f of a.appearsIn) assert.match(f, /^knowledge\//, 'each must be a real corpus path');
});

test('the mechanism of the error is Spanish, and is stated', () => {
  const a = ARTIFACTS.find((x) => x.id === 'aztec-tiger');
  assert.match(a.howTheErrorEnters, /Spanish/);
  assert.match(a.howTheErrorEnters, /tigre/);
});

test('a DISSOLVED artefact must state what it does NOT touch — no overclaiming', () => {
  for (const a of dissolved()) {
    assert.ok(a.scope, `${a.id} dissolves a claim without bounding the consequence`);
  }
  const t = ARTIFACTS.find((x) => x.id === 'aztec-tiger');
  assert.match(t.scope, /does not/i, 'the scope line must limit the finding, not extend it');
});

test('every artefact records what it was verified against', () => {
  for (const a of ARTIFACTS) {
    assert.ok(a.verifiedAgainst, `${a.id} has no verification`);
    assert.ok(a.verifiedAgainst.length > 20, `${a.id} verification is too thin to check`);
  }
});

test('the ocelot/jaguar word confusion is recorded separately — it is why the error is believable', () => {
  const o = ARTIFACTS.find((x) => x.id === 'ocelot-the-cat');
  assert.equal(o.verdict, 'dissolved');
  assert.match(o.howTheErrorEnters, /Leopardus pardalis/);
});

test('the Chinese animal layer is dated separately from the branches, and is only PARTIAL', () => {
  const c = ARTIFACTS.find((x) => x.id === 'chinese-animal-antiquity');
  assert.equal(c.verdict, 'partial', 'dating a layer is not the same as dissolving a system');
  const sys = getSystem('earthly-branches');
  assert.match(sys.note, /⚠️/);
  assert.match(sys.note, /later overlay|thousand years/i);
});

// --- the comparison tool warns about itself ----------------------------------

test('sharedAnimals matches on ENGLISH and says so — that is the very operation that made the error', () => {
  const r = sharedAnimals();
  assert.ok(Array.isArray(r.shared));
  assert.match(r.warning, /english/i);
  assert.match(r.warning, /4 Tiger|tiger/i, 'the warning must name the error it descends from');
});

test('the tiger does NOT appear as a shared animal, because the Aztec list has none', () => {
  const r = sharedAnimals();
  assert.ok(!r.shared.some((x) => /tiger/i.test(x.animal)),
    'a shared "tiger" row would be the original error, regenerated by this very function');
});

// --- gods of the hour --------------------------------------------------------

test('hourGods returns the systems that assign a deity to a unit of time', () => {
  const h = hourGods().map((s) => s.id);
  assert.ok(h.includes('decans'), 'the decans are the original hour-gods');
  assert.ok(h.includes('lords-of-the-night'), 'the Nine Lords are the American parallel');
  assert.ok(h.includes('planetary-hours'));
});

test('the horā records a DOCUMENTED transmission — the loanword travels with the technique', () => {
  const h = getSystem('hora');
  assert.match(h.note, /horā is the Greek|ὥρα|Greek hōra/i);
  assert.match(h.note, /⭐/);
});

test('the planetary hours record the one system that provably generated another', () => {
  const p = getSystem('planetary-hours');
  assert.match(p.note, /week/i);
  assert.match(p.source, /Dio Cassius/);
});

// --- lookups and robustness --------------------------------------------------

test('getSystem is exact and case-insensitive; unknown returns null, never a guess', () => {
  assert.ok(getSystem('DECANS'));
  assert.equal(getSystem('decan'), null);
  assert.equal(getSystem('nonsense'), null);
});

test('traditions are derived, deduped and sorted', () => {
  assert.deepEqual(TRADITIONS, [...new Set(TRADITIONS)].sort());
  assert.ok(byTradition('aztec').length >= 2);
});

test('nothing throws on junk', () => {
  for (const v of [null, undefined, 0, '', [], {}]) {
    assert.doesNotThrow(() => getSystem(v));
    assert.doesNotThrow(() => byTradition(v));
    assert.doesNotThrow(() => esc(v));
  }
  assert.doesNotThrow(() => sharedAnimals());
  assert.doesNotThrow(() => artifacts());
});

test('handler serves the counts and the one-line correction', () => {
  let body = '';
  handler({}, { statusCode: 0, setHeader() {}, end(b) { body = b; } });
  const j = JSON.parse(body);
  assert.equal(j.ok, true);
  assert.match(j.note, /jaguar/);
});
