// vtt-srt-parse.test.mjs — offline tests for the SRT/WebVTT → transcript parser.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  detectFormat,
  parse,
  toPlainText,
  timecodeToMs,
  msToTimecode,
} from './vtt-srt-parse.mjs';

const SRT = `1
00:00:01,000 --> 00:00:04,000
Hello and welcome.

2
00:00:04,500 --> 00:00:07,200
This is the <i>second</i> line
spanning two rows.

3
00:00:07,200 --> 00:00:09,000
Goodbye.
`;

const VTT = `WEBVTT
Kind: captions
Language: en

NOTE
This file was generated by an auto-captioner.

STYLE
::cue { color: white }

00:00:00.000 --> 00:00:02.000
<c>Welcome</c> to the show.

00:00:02.000 --> 00:00:04.000
Today we talk about MELEK.
`;

// auto-caption rolling repeat: same line emitted across consecutive cues
const VTT_DUP = `WEBVTT

00:00:00.000 --> 00:00:01.500
rolling line one

00:00:01.500 --> 00:00:03.000
rolling line one

00:00:03.000 --> 00:00:04.500
rolling line two
`;

test('detectFormat distinguishes srt / vtt / unknown', () => {
  assert.equal(detectFormat(SRT), 'srt');
  assert.equal(detectFormat(VTT), 'vtt');
  assert.equal(detectFormat('just some prose with no cues'), 'unknown');
  assert.equal(detectFormat(''), 'unknown');
  assert.equal(detectFormat(null), 'unknown');
  // dotted decimals without WEBVTT header still read as vtt
  assert.equal(detectFormat('00:00:01.000 --> 00:00:02.000\nhi'), 'vtt');
});

test('parse SRT: index/timing/joined-multiline/stripped tags', () => {
  const cues = parse(SRT);
  assert.equal(cues.length, 3);
  assert.deepEqual(cues[0], { index: 0, startMs: 1000, endMs: 4000, text: 'Hello and welcome.' });
  assert.equal(cues[1].text, 'This is the second line spanning two rows.'); // <i> stripped, rows joined
  assert.equal(cues[1].startMs, 4500);
  assert.equal(cues[1].endMs, 7200);
});

test('parse VTT: strips WEBVTT/NOTE/STYLE, keeps real cues, strips <c>', () => {
  const cues = parse(VTT);
  assert.equal(cues.length, 2);
  assert.equal(cues[0].text, 'Welcome to the show.');
  assert.equal(cues[0].startMs, 0);
  assert.equal(cues[0].endMs, 2000);
  assert.equal(cues[1].text, 'Today we talk about MELEK.');
  // indices are sequential after header/NOTE/STYLE removal
  assert.deepEqual(cues.map((c) => c.index), [0, 1]);
});

test('toPlainText dedupes consecutive identical lines (auto-captions)', () => {
  const cues = parse(VTT_DUP);
  assert.equal(cues.length, 3);
  assert.equal(toPlainText(cues), 'rolling line one rolling line two');
  // dedupe off keeps the repeat
  assert.equal(toPlainText(cues, { dedupe: false }), 'rolling line one rolling line one rolling line two');
  // custom joiner
  assert.equal(toPlainText(cues, { join: '\n' }), 'rolling line one\nrolling line two');
});

test('timecode round-trip and both decimal separators', () => {
  assert.equal(timecodeToMs('01:02:03,456'), ((1 * 3600 + 2 * 60 + 3) * 1000) + 456);
  assert.equal(timecodeToMs('01:02:03.456'), ((1 * 3600 + 2 * 60 + 3) * 1000) + 456);
  assert.equal(timecodeToMs('02:03.500'), ((2 * 60 + 3) * 1000) + 500); // MM:SS.mmm, no hours
  const ms = 3723456;
  assert.equal(msToTimecode(ms), '01:02:03.456');
  assert.equal(timecodeToMs(msToTimecode(ms)), ms); // round-trip
  assert.equal(msToTimecode(0), '00:00:00.000');
});

test('soft-fail: malformed input never throws', () => {
  assert.deepEqual(parse(null), []);
  assert.deepEqual(parse(''), []);
  assert.deepEqual(parse('garbage with no timing line\nat all'), []);
  // malformed timing inside an otherwise-fine file → that cue skipped, others kept
  const mixed = `1
00:00:01,000 --> 00:00:02,000
good cue

2
99:99 --> nonsense
bad cue

3
00:00:03,000 --> 00:00:04,000
another good cue
`;
  const cues = parse(mixed);
  assert.equal(cues.length, 2);
  assert.equal(cues[0].text, 'good cue');
  assert.equal(cues[1].text, 'another good cue');
  // bad timecodes
  assert.ok(Number.isNaN(timecodeToMs('not a time')));
  assert.ok(Number.isNaN(timecodeToMs(null)));
  // msToTimecode clamps bad input
  assert.equal(msToTimecode(-5), '00:00:00.000');
  assert.equal(msToTimecode(NaN), '00:00:00.000');
  // toPlainText tolerates non-array / bad cues
  assert.equal(toPlainText(null), '');
  assert.equal(toPlainText([{ text: 'a' }, null, { text: '' }, { nope: 1 }, { text: 'b' }]), 'a b');
});
