// mediawikiSetup.js — config + runbook generator for standing up a real MediaWiki + bot account
// for the Library of Ashurbanipal (task #93).
//
// The library bot today renders MediaWiki markup (src/wikiGenerator.js → src/mwRender.js) and serves
// it itself. The UPGRADE PATH is to host that output on a real MediaWiki instance that the
// Ashurbanipal bot edits via the API. This module is the DETERMINISTIC CONFIG / RUNBOOK GENERATOR for
// that stand-up — NOT a deployer. It emits:
//   - localSettingsConfig({...}) : a MediaWiki LocalSettings.php-shaped object + rendered PHP string
//                                  that references env var NAMES only (DB creds, secret key)
//   - botAccountPlan({...})      : the least-privilege plan for the Ashurbanipal bot account
//   - setupRunbook()             : a markdown runbook (install / env / bot account / DNS / Caddy /
//                                  hardening)
//   - requiredEnv()              : the env var NAMES the deploy needs
//   - validateConfig(cfg)        : { ok, errors[] } incl. a scan that no secret literal slipped in
//
// CONVENTIONS (match the library bot — see forum-setup.mjs for the sibling MyBB version):
//   - ESM (package.json "type":"module"), like every other src/ module.
//   - PURE + DETERMINISTIC: no network, no fs, no clock. Same input → same output.
//   - SOFT-FAIL: bad input never throws; returns a result object / safe default.
//   - NO SECRETS: database password, bot password, and the wiki secret key are referenced as env var
//     NAMES only. Their VALUES are read by the deploy step from the environment / vault, never here
//     and never committed.
//   - CLI GUARDED: importing this module has no side effects; the CLI block only runs when invoked
//     directly.
//
// Run the tests: node --test test/mediawikiSetup.test.js

// ---------------------------------------------------------------------------
// Defaults. Note every credential field is an env var NAME, not a value.
// ---------------------------------------------------------------------------
const DEFAULT_OPTS = {
  siteName: 'Library of Ashurbanipal',
  server: 'https://wiki.soapbox.community',
  dbHostEnv: 'WIKI_DB_HOST',
  dbNameEnv: 'WIKI_DB_NAME',
  dbUserEnv: 'WIKI_DB_USER',
  dbPassEnv: 'WIKI_DB_PASS',
  secretKeyEnv: 'WIKI_SECRET_KEY',
};

// The Ashurbanipal bot account default. The bot's BotPasswords secret lives ONLY in the env/vault.
const DEFAULT_BOT_NAME = 'Ashurbanipal';
const DEFAULT_BOT_PASSWORD_ENV = 'WIKI_BOT_PASSWORD';

// ---------------------------------------------------------------------------
// LocalSettings.php generator.
//
// MediaWiki stores its DB credentials and the wiki secret key in LocalSettings.php. We DO NOT embed
// any secret value. The generated file reads each from the process environment at runtime via
// getenv('NAME'), so the only thing this generator (and the repo) ever contains is the env var NAMES.
// The deploy step is responsible for populating those vars (from the vault) when PHP runs.
// ---------------------------------------------------------------------------
/**
 * Build a MediaWiki LocalSettings.php-shaped object plus the rendered PHP string.
 * All credential / secret fields reference env var NAMES — never values. Soft-fails to defaults.
 * Enables the API and bot-friendly editing ($wgEnableAPI, $wgGroupPermissions for bot, etc.).
 * @returns {{ object: object, php: string, envVarsRequired: string[] }}
 */
export function localSettingsConfig(opts = {}) {
  const o = { ...DEFAULT_OPTS, ...(opts && typeof opts === 'object' ? opts : {}) };

  // Structured object a deploy step consumes. The *Env fields are env var NAMES; the deploy step
  // resolves them. We never put the secret value here.
  const object = {
    siteName: String(o.siteName),
    server: String(o.server),
    database: {
      type: 'mysql',
      hostEnv: String(o.dbHostEnv),
      nameEnv: String(o.dbNameEnv),
      userEnv: String(o.dbUserEnv),
      passwordEnv: String(o.dbPassEnv),
    },
    secretKeyEnv: String(o.secretKeyEnv),
    // API + bot-friendly settings.
    api: {
      enableApi: true,
      enableWriteApi: true,
    },
  };

  // getenv('NAME') reads the secret AT RUNTIME — the literal in the file is the NAME, not the value.
  const g = (name) => `getenv('${String(name)}')`;

  const php = `<?php
/**
 * LocalSettings.php for ${object.siteName} (${object.server})
 *
 * GENERATED by src/mediawikiSetup.js — review before use.
 * Database credentials and the wiki secret key are read from the ENVIRONMENT at runtime.
 * No secret values appear in this file or in the repo; only the env var NAMES below.
 * The deploy step must export these vars (from the vault) before PHP runs:
 *   ${object.database.hostEnv}, ${object.database.nameEnv}, ${object.database.userEnv}, ${object.database.passwordEnv}, ${object.secretKeyEnv}
 */
if ( !defined( 'MEDIAWIKI' ) ) { exit; }

$wgSitename = ${JSON.stringify(object.siteName)};
$wgMetaNamespace = "Library_of_Ashurbanipal";
$wgServer = ${JSON.stringify(object.server)};

$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

## Database — credentials come from the environment, never hard-coded.
$wgDBtype = "mysql";
$wgDBserver = ${g(object.database.hostEnv)};
$wgDBname = ${g(object.database.nameEnv)};
$wgDBuser = ${g(object.database.userEnv)};
$wgDBpassword = ${g(object.database.passwordEnv)};
$wgDBprefix = "";

## Secret key — read from the environment (vault), never committed.
$wgSecretKey = ${g(object.secretKeyEnv)};
$wgUpgradeKey = ${g(object.secretKeyEnv)};

## ---- API + bot-friendly settings ----
# The Action API must be enabled so the Ashurbanipal bot can edit programmatically.
$wgEnableAPI = true;        # (default true on modern MediaWiki; set explicitly for clarity)
$wgEnableWriteAPI = true;   # allow write actions (edit/create) over the API
# BotPasswords are how a bot authenticates with a scoped, revocable secret (not the account password).
$wgEnableBotPasswords = true;
# The 'bot' group flags edits as bot edits (hidden from RecentChanges by default) and raises rate caps.
$wgGroupPermissions['bot']['edit'] = true;
$wgGroupPermissions['bot']['createpage'] = true;
$wgGroupPermissions['bot']['createtalk'] = true;
$wgGroupPermissions['bot']['writeapi'] = true;
$wgGroupPermissions['bot']['bot'] = true;
$wgGroupPermissions['bot']['apihighlimits'] = true;
# Least privilege: the bot is NOT a sysop and CANNOT delete.
$wgGroupPermissions['bot']['delete'] = false;
$wgGroupPermissions['bot']['protect'] = false;

## ---- Security hardening ----
# No anonymous (logged-out) edits — content is written by the bot + reviewed editors only.
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = false; # accounts are created by an admin, not self-serve
# Throttle account-creation and edits to blunt spam/abuse.
$wgAccountCreationThrottle = 0; # self-serve creation is off anyway
$wgRateLimits['edit']['user'] = [ 60, 60 ];   # 60 edits / 60s for normal users
$wgRateLimits['edit']['newbie'] = [ 8, 60 ];

## Uploads off unless explicitly needed (smaller attack surface).
$wgEnableUploads = false;

## Skin.
wfLoadSkin( 'Vector' );
`;

  return {
    object,
    php,
    envVarsRequired: [
      object.database.hostEnv,
      object.database.nameEnv,
      object.database.userEnv,
      object.database.passwordEnv,
      object.secretKeyEnv,
    ],
  };
}

// ---------------------------------------------------------------------------
// Bot account plan.
//
// The Ashurbanipal bot authenticates via MediaWiki BotPasswords: a named, scoped, individually
// revocable credential tied to the account — NOT the account's main password. We grant only the
// rights the bot needs to publish wiki articles (edit existing + create new pages) and explicitly
// withhold sysop/delete/protect. The bot password VALUE lives in the vault/env, never committed.
// ---------------------------------------------------------------------------
/**
 * The least-privilege plan for the Ashurbanipal bot account.
 * Returns a structured object (no secrets — the password is referenced by env var NAME only).
 * @returns {object}
 */
export function botAccountPlan(opts = {}) {
  const o = opts && typeof opts === 'object' ? opts : {};
  const botName = (typeof o.botName === 'string' && o.botName.trim()) ? o.botName.trim() : DEFAULT_BOT_NAME;
  const passwordEnv = (typeof o.passwordEnv === 'string' && o.passwordEnv.trim())
    ? o.passwordEnv.trim()
    : DEFAULT_BOT_PASSWORD_ENV;

  // Grants the bot NEEDS — publishing wiki articles only.
  const grants = ['edit', 'createpage'];
  // Rights explicitly DENIED — least privilege. The bot is not an administrator.
  const deniedGrants = ['sysop', 'delete', 'protect', 'block', 'createaccount', 'import', 'editsitecss', 'editsitejs'];

  return {
    botName,
    // The on-wiki account belongs to the 'bot' group (bot-flagged edits + higher API limits).
    group: 'bot',
    // BotPasswords credential: a named, scoped, revocable secret distinct from the login password.
    botPassword: {
      label: `${botName}@publisher`, // appears as "Username@label" when authenticating
      // GRANTS — least privilege: enough to publish articles, nothing more.
      grants,
      // Explicitly NOT granted. Asserted in tests; documents the boundary.
      deniedGrants,
      // The secret VALUE is never here. It lives in the vault and is exported as this env var.
      secretEnv: passwordEnv,
      revocable: true,
    },
    principleOfLeastPrivilege:
      'The bot can edit existing pages and create new ones — exactly what publishing the synthesized ' +
      'wiki output requires. It is NOT a sysop and cannot delete, protect, block, import, or create ' +
      'accounts. A BotPasswords credential is scoped and individually revocable, so a leak is ' +
      'contained and killable without touching the account password.',
    secretsLocation:
      `The bot password is generated once via Special:BotPasswords, stored in the operator vault ` +
      `(Vaultwarden), and exported to the deploy environment as ${passwordEnv}. It is NEVER committed ` +
      `to this repo and never logged.`,
  };
}

// ---------------------------------------------------------------------------
// Setup runbook (markdown). Static, deterministic text.
// ---------------------------------------------------------------------------
/** Markdown runbook for installing + securing MediaWiki and the Ashurbanipal bot account. */
export function setupRunbook() {
  const plan = botAccountPlan();
  return `# ${DEFAULT_OPTS.siteName} — MediaWiki setup runbook

> GENERATED by src/mediawikiSetup.js. This is a runbook, not an automated deployer.
> Do every step deliberately. No secrets live in this repo — they come from the vault / environment.

This stands up a real MediaWiki that hosts the output of the library bot's wiki generator
(\`src/wikiGenerator.js\` → \`src/mwRender.js\`). The **Ashurbanipal** bot publishes to it via the
Action API using a scoped, least-privilege BotPasswords credential.

## 1. Provision MediaWiki
1. Download the latest stable MediaWiki release from https://www.mediawiki.org/ and verify its checksum.
2. Install PHP (with the mysqli + intl + mbstring extensions) and MariaDB/MySQL on the wiki host.
3. Create the wiki database and a dedicated DB user with rights on **that database ONLY**.
4. Run the web installer once to lay down the schema, then generate \`LocalSettings.php\` with
   \`localSettingsConfig({...})\` from this module. It reads DB credentials and the wiki secret key
   from environment variables at runtime — populate them from the vault (see §5), never hard-code them.
5. Place \`LocalSettings.php\` in the MediaWiki root and \`chmod\` it to 0640, owned by the web user.

## 2. Configure LocalSettings via env
- \`localSettingsConfig()\` emits PHP whose credential lines are \`getenv('NAME')\` calls — the file
  contains only env var **names**, never secret values.
- Confirm the deploy environment (PHP-FPM pool \`environment\` directives, or systemd \`Environment=\`)
  exports every name from \`requiredEnv()\` before the first request.
- The config enables the Action API (\`$wgEnableAPI\` / \`$wgEnableWriteAPI\`) and the \`bot\` group so
  the Ashurbanipal bot can edit programmatically.

## 3. Create the bot account + BotPasswords (least privilege)
1. As an admin, create the on-wiki account **${plan.botName}** and add it to the \`${plan.group}\` group.
2. Log in as that account and open **Special:BotPasswords**.
3. Create a BotPassword labelled \`${plan.botPassword.label}\` granting ONLY:
   ${plan.botPassword.grants.map((g) => `\`${g}\``).join(', ')}.
4. Do **NOT** grant: ${plan.botPassword.deniedGrants.map((g) => `\`${g}\``).join(', ')}.
   ${plan.principleOfLeastPrivilege}
5. Copy the generated secret ONCE into the vault and export it to the deploy env as
   \`${plan.botPassword.secretEnv}\`. ${plan.secretsLocation}
6. The bot authenticates as \`${plan.botName}@publisher\` using \`${plan.botPassword.secretEnv}\`.
   Because BotPasswords are individually revocable, a leak is contained — revoke and reissue without
   touching the account's main password.

## 4. DNS (generic — not host-specific)
- At your DNS provider, add an **A record** for the wiki subdomain → the wiki host's public IPv4
  (and an **AAAA** record if the host has IPv6).
- Use a short TTL (~300s) during setup; raise it once stable.
- Point it the same way the other SoapBox subdomains are pointed (this runbook is host-agnostic).

## 5. Reverse proxy (Caddy TLS)
Caddy terminates TLS (automatic Let's Encrypt) and proxies to PHP-FPM.

\`\`\`caddy
wiki.soapbox.community {
    encode zstd gzip
    root * /var/www/mediawiki
    php_fastcgi unix//run/php/php-fpm.sock
    file_server

    # Pretty URLs: /wiki/Page → index.php.
    @wiki path /wiki/*
    rewrite @wiki /index.php?title={path}

    # Block direct access to sensitive paths.
    @blocked path /cache/* /images/deleted/* /maintenance/* /LocalSettings.php
    respond @blocked 403

    header {
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
    }
}
\`\`\`

Reload Caddy after editing: \`caddy reload\`. This is the same Caddy-TLS + UFW 80/443 pattern used for
data.soapbox.community on the SoapBox host.

## 6. Security hardening checklist
- [ ] **No anonymous edits** — \`$wgGroupPermissions['*']['edit'] = false\` (set in the config).
- [ ] **No self-serve account creation** — accounts are created by an admin only.
- [ ] **Least-privilege bot** — the Ashurbanipal bot has \`edit\` + \`createpage\` only; **no sysop, no
      delete, no protect**. Asserted in \`botAccountPlan()\`.
- [ ] **Rate limits** on edits (\`$wgRateLimits\`) to blunt runaway/abusive editing.
- [ ] Uploads disabled (\`$wgEnableUploads = false\`) unless explicitly needed.
- [ ] \`chmod\` \`LocalSettings.php\` to 0640, owned by the web user; block it in Caddy.
- [ ] Keep MediaWiki + extensions patched; subscribe to MediaWiki security advisories.
- [ ] UFW: allow only 80/443 (and SSH from known IPs); deny everything else.
- [ ] Off-host, encrypted DB backups; test a restore.
- [ ] CrowdSec / fail2ban for repeated failed logins.

## 7. Where secrets come from (vault, never committed)
Database credentials, the wiki secret key, and the bot password are **NEVER committed**. They live in
the operator's vault (Vaultwarden) and are exported as environment variables on the wiki host at
deploy time. The generated \`LocalSettings.php\` reads each via \`getenv('NAME')\`; the bot reads its
password from the env. Confirm every name from \`requiredEnv()\` is present in the PHP-FPM / bot
environment before going live.
`;
}

// ---------------------------------------------------------------------------
// Required env var NAMES for the deploy. Combines the LocalSettings names + the bot password name.
// ---------------------------------------------------------------------------
/**
 * The env var NAMES the deploy needs (DB host/name/user/pass, secret key, bot password).
 * @returns {string[]}
 */
export function requiredEnv() {
  const { envVarsRequired } = localSettingsConfig();
  const { botPassword } = botAccountPlan();
  return [...envVarsRequired, botPassword.secretEnv];
}

// ---------------------------------------------------------------------------
// Validation.
//
// Structural checks PLUS a defence-in-depth scan that no secret LITERAL slipped into the config. A
// credential field that is supposed to be an env var NAME but instead holds something password-shaped
// (long, with mixed case/digits/symbols, or an obvious 'password=' assignment) is flagged.
// ---------------------------------------------------------------------------
const ENV_NAME_RE = /^[A-Z][A-Z0-9_]*$/; // conventional SCREAMING_SNAKE env var name

/**
 * Heuristic: does this string look like a secret VALUE rather than an env var NAME?
 * Env var names are SCREAMING_SNAKE_CASE. Anything that isn't, but is long / mixed / symbol-laden,
 * is treated as a possible leaked secret.
 * @param {string} s
 * @returns {boolean}
 */
function looksLikeSecretLiteral(s) {
  if (typeof s !== 'string') return false;
  const v = s.trim();
  if (!v) return false;
  if (ENV_NAME_RE.test(v)) return false; // a proper env var NAME is fine
  // 'password = "...."' / 'getenv(...)' literal embedded? Common secret-assignment shapes.
  if (/(pass(word)?|secret|token|key)\s*[:=]\s*\S/i.test(v)) return true;
  // High-entropy-ish: long string mixing cases + digits (and maybe symbols) and no spaces.
  const noSpace = !/\s/.test(v);
  const mixed = /[a-z]/.test(v) && /[A-Z0-9]/.test(v);
  if (noSpace && mixed && v.length >= 12) return true;
  return false;
}

/**
 * Validate a config object (the shape returned by localSettingsConfig().object, or a raw opts obj).
 * Returns { ok, errors[] }. Never throws. Includes a check that NO secret literal slipped in.
 * @param {object} cfg
 * @returns {{ ok: boolean, errors: string[] }}
 */
export function validateConfig(cfg) {
  const errors = [];
  if (!cfg || typeof cfg !== 'object') {
    return { ok: false, errors: ['config must be an object'] };
  }

  // Accept either the structured object (with .database.*Env) or a raw opts object (dbHostEnv, ...).
  const credEnvFields = [];
  if (cfg.database && typeof cfg.database === 'object') {
    credEnvFields.push(
      ['database.hostEnv', cfg.database.hostEnv],
      ['database.nameEnv', cfg.database.nameEnv],
      ['database.userEnv', cfg.database.userEnv],
      ['database.passwordEnv', cfg.database.passwordEnv],
    );
  } else {
    credEnvFields.push(
      ['dbHostEnv', cfg.dbHostEnv],
      ['dbNameEnv', cfg.dbNameEnv],
      ['dbUserEnv', cfg.dbUserEnv],
      ['dbPassEnv', cfg.dbPassEnv],
    );
  }
  credEnvFields.push(['secretKeyEnv', cfg.secretKeyEnv]);

  for (const [field, val] of credEnvFields) {
    if (val == null) {
      errors.push(`${field} is missing (expected an env var NAME)`);
      continue;
    }
    if (typeof val !== 'string') {
      errors.push(`${field} must be a string env var NAME`);
      continue;
    }
    if (looksLikeSecretLiteral(val)) {
      errors.push(`${field} looks like a hardcoded secret literal — use an env var NAME instead`);
    } else if (!ENV_NAME_RE.test(val.trim())) {
      errors.push(`${field} "${val}" is not a valid env var NAME (expected SCREAMING_SNAKE_CASE)`);
    }
  }

  // Scan the rendered PHP too, if present, for an embedded secret assignment with a literal value.
  if (typeof cfg.php === 'string' && /(\$wgDBpassword|\$wgSecretKey)\s*=\s*["'][^"']+["']/.test(cfg.php)) {
    errors.push('rendered PHP contains a hardcoded credential literal (must be getenv(...))');
  }

  // Basic shape checks.
  if (cfg.siteName != null && (typeof cfg.siteName !== 'string' || !cfg.siteName.trim())) {
    errors.push('siteName must be a non-empty string');
  }
  if (cfg.server != null && typeof cfg.server === 'string' && cfg.server.trim() && !/^https?:\/\//i.test(cfg.server.trim())) {
    errors.push('server must be an http(s) URL');
  }

  return { ok: errors.length === 0, errors };
}

// ---------------------------------------------------------------------------
// CLI — print the config + bot plan + runbook. Guarded so importing has no side effects.
// ---------------------------------------------------------------------------
if (process.argv[1] && process.argv[1].endsWith('mediawikiSetup.js')) {
  const cfg = localSettingsConfig();
  const v = validateConfig(cfg.object);
  if (!v.ok) {
    console.error('config validation failed:', v.errors);
  } else {
    console.log('# config validates (env var NAMES only).\n');
    console.log('# ---- LocalSettings.php (env var NAMES only) ----');
    console.log(cfg.php);
    console.log('\n# ---- bot account plan (least privilege) ----');
    console.log(JSON.stringify(botAccountPlan(), null, 2));
    console.log('\n# ---- required env ----');
    console.log(requiredEnv().join('\n'));
    console.log('\n# ---- setup runbook ----');
    console.log(setupRunbook());
  }
}

export default {
  localSettingsConfig,
  botAccountPlan,
  setupRunbook,
  requiredEnv,
  validateConfig,
};
