import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  entrainmentTracks, byType, byState, toTrack, toTile, bandName, renderList, dataNote,
  SAFETY_NOTE, TYPES, STATES, ENTRAINMENT_BASE, esc,
} from './entrainment.mjs';

test('esc escapes html incl quotes', () => {
  assert.equal(esc(`<b>&"'`), '&lt;b&gt;&amp;&quot;&#39;');
});

test('curated set: 6 tracks, all Hathor-attributed, CC0, host posture', () => {
  const t = entrainmentTracks();
  assert.equal(t.length, 6);
  for (const x of t) {
    assert.equal(x.artist, 'Hathor');            // operator attribution rule
    assert.equal(x.creator, 'Hathor');
    assert.equal(x.license, 'CC0');              // generated original, ours by construction
    assert.equal(x.posture, 'host');
    assert.equal(x.safety, SAFETY_NOTE);
    assert.ok(x.streamUrl.startsWith(ENTRAINMENT_BASE));
    assert.ok(x.streamUrl.endsWith('.opus'));
  }
});

test('has the required frequencies incl the 40 Hz gamma track', () => {
  const freqs = entrainmentTracks().map((x) => x.freqHz).sort((a, b) => a - b);
  assert.deepEqual(freqs, [2.5, 6, 7.83, 10, 18, 40]);
});

test('at least one binaural AND one isochronic; binaural needs headphones', () => {
  assert.ok(byType('binaural').length >= 1);
  assert.ok(byType('isochronic').length >= 1);
  for (const x of byType('binaural')) assert.equal(x.headphones, true);
  for (const x of byType('isochronic')) assert.equal(x.headphones, false);
});

test('40 Hz track is isochronic (speaker-friendly) and tagged Focus/Gamma', () => {
  const g = entrainmentTracks().find((x) => x.freqHz === 40);
  assert.equal(g.type, 'isochronic');
  assert.equal(g.headphones, false);
  assert.equal(g.state, 'Focus');
  assert.match(g.title, /Gamma/);
});

test('states are named by STATE, never a drug name', () => {
  const states = entrainmentTracks().map((x) => x.state);
  assert.deepEqual([...new Set(states)].sort(), [...STATES].sort());
  for (const s of states) assert.ok(STATES.includes(s));
});

test('bandName buckets frequencies honestly', () => {
  assert.equal(bandName(2.5), 'Delta');
  assert.equal(bandName(6), 'Theta');
  assert.equal(bandName(10), 'Alpha');
  assert.equal(bandName(18), 'Beta');
  assert.equal(bandName(40), 'Gamma');
});

test('byState filters case-insensitively', () => {
  assert.equal(byState('sleep').length, 1);
  assert.equal(byState('SLEEP')[0].freqHz, 2.5);
  assert.equal(byState('nope').length, 0);
});

test('toTrack soft-handles junk', () => {
  assert.equal(toTrack(null), null);
  assert.equal(toTrack({}), null);
});

test('toTile maps to the surface tile shape (host posture, direct audio href)', () => {
  const tile = toTile(entrainmentTracks()[0]);
  assert.equal(tile.kind, 'entrainment');
  assert.equal(tile.posture, 'host');
  assert.equal(tile.artist, 'Hathor');
  assert.ok(tile.href.endsWith('.opus'));
});

test('renderList emits esc-safe rows, the Hathor byline, and the safety note', () => {
  const html = renderList();
  assert.match(html, /original tones by Hathor/);
  assert.match(html, /40 Hz/);
  assert.match(html, /<audio controls/);
  assert.match(html, /not medical treatment/);
  // no drug-name or "digital drug" claims anywhere in the surface
  assert.doesNotMatch(html.toLowerCase(), /digital drug|dose|high\b/);
});

test('SAFETY_NOTE carries the load-bearing warnings', () => {
  assert.match(SAFETY_NOTE, /not medical treatment/i);
  assert.match(SAFETY_NOTE, /driving|machinery/i);
  assert.match(SAFETY_NOTE, /epilep|seizure/i);
  assert.match(SAFETY_NOTE, /pacemaker/i);
  assert.match(SAFETY_NOTE, /headphones/i);
});

test('dataNote states the generated-original / not-treatment posture', () => {
  assert.match(dataNote(), /generated by Hathor/i);
  assert.match(dataNote(), /not medical treatment/i);
});
